### PR TITLE
wizard / secvisogram 2.0

### PR DESCRIPTION
**Pull request by valentinkoe**
This brings the new `FormEditor` and updated JSON editor as well as connecting with the [CSAF CMS backend](https://github.com/secvisogram/csaf-cms-backend/)

### CODE REVIEW

**Review by tschmidtb51 — CHANGES_REQUESTED** [review]
I didn't do the full review yet but I already noticed that the LICENSE.md was not yet updated. See https://github.com/secvisogram/secvisogram/blob/feat/wizzard/LICENSE.md#third-party-library-licenses for instructions...

**Review by tschmidtb51 — CHANGES_REQUESTED** [review]
I updated the license file - so that issue is resolved. However, #422 came up. As discussed with Mr Hermann this should be resolved. Questions via phone....

**Comment by tschmidtb51** [comment]
@mfd2007 Could you please check that the scrollbar in the Preview works if Rendered is selected? All others (even the source) on works but that one fails currently for me.

**Comment by mfd2007** [comment]
@tschmidtb51 

> @mfd2007 Could you please check that the scrollbar in the Preview works if Rendered is selected? All others (even the source) on works but that one fails currently for me.

I can confirm the problem.

**Review by tschmidtb51 — APPROVED** [review]
LGTM and works

**Review by cloeser — APPROVED** [review]

**Pull request merged**
