### PR TITLE
added load from URL feature

### PR DESCRIPTION
**Pull request by MarcoKorinth**
added feature to load json file from URL, which can be done in the "New"-Dialog.
Original issue: https://github.com/secvisogram/secvisogram/issues/313

### CODE REVIEW

**Review by StefanNemeth — CHANGES_REQUESTED** [review]
Seems good to me, for further features we will pull the changes from our fork though. You would still need to update `SECURITY-CONSIDERATIONS.md`, potentially in multiple places, e.g. in "1. Injection".

+ it would be good if you provided an URL to test the changes

One issue I had was replacing the document twice,
1. removing the content
2. load from URL
3. removing the content
4. load from URL again
5. content does not get replaced again

However, that seems to be the case even before this change (including loading the document from a local file), so it might be the wanted behavior.

**Comment by tschmidtb51** [comment]
> One issue I had was replacing the document twice,
> 
>     1. removing the content
> 
>     2. load from URL
> 
>     3. removing the content
> 
>     4. load from URL again
> 
>     5. content does not get replaced again
> 
> 
> However, that seems to be the case even before this change (including loading the document from a local file), so it might be the wanted behavior.

I can't simulate that one with the version currently only (replaced `load from url` with `load from file`). Maybe something for Friday?

**Comment by tschmidtb51** [comment]
> * it would be good if you provided an URL to test the changes

At the time of writing:
- https://sick.com/.well-known/csaf/white/2023/sca-2023-0001.json works
- https://wid.cert-bund.de/.well-known/csaf/white/2022/bsi-2022-0001.json doesn't work

**Comment by MarcoKorinth** [comment]
I separated the error messages.
And my previous assumption was right, it's not possible to distinguish between different network errors.
Do you still want to include information about CORS in the README file @tschmidtb51?

**Review by tschmidtb51 — CHANGES_REQUESTED** [review]
Some minor documentation changes. Other than that: LGTM

**Review by tschmidtb51 — APPROVED** [review]
LGTM

**Pull request merged**
