### PR TITLE
Fix datepicker

### PR DESCRIPTION
**Pull request by domachine**
This addresses the bug described in #9.

### CODE REVIEW

**Review by sthagen — APPROVED** [review]

**Review by bentolor — APPROVED** [review]
Confirmed working in Firefox & Chrome as well as Safari according to https://github.com/secvisogram/secvisogram/issues/9#issuecomment-877644144

**Comment by bentolor** [comment]
Positively reviewed by me and sthagen. Please review changes &  approve merge, @tschmidtb51

**Comment by tschmidtb51** [comment]
@bentolor IMHO, I found a bug:

If you use the attached document [SEC_2021_0001_160_invalid.json](https://github.com/secvisogram/secvisogram/files/6803043/SEC_2021_0001_160_invalid.json.txt) (Sorry, needed to upload as txt as GitHub does not support JSON as attached documents.) and try to update the `Initial release date` via the Form editor calendar dropdown - it fails. If you type the date in, it does this weird thing with overwriting values as we had also during our initial development. This applies also to the time part.

Can someone confirm this?

My expectation would be that it overwrites the invalid value (or retrieves the date part from the given value but I don't want to make that overly complex) and applies the rules for setting the time afterwards.

**Comment by bentolor** [comment]
@tschmidtb51  I can confirm:
* Loading correctly reports `Should match format "date-time"`
* In this state, date picker is not available (IMHO, should be)
* In this state, typing date clears entries, after first number in the year field (i.e. you type `01012020`. If you start over, it is possible to enter a date in an unsatisfactory way.

This bug also seems to already present in `v1.1.3`

IMHO the fix should be, that if the JSON value does not correctly resolve into a datetime, the date picker should start with an empty value. 

Not sure if this can be be achieved easily to delay the erasure of this invalid date value to the moment where the user clicks first on the date picker widget. Will discuss with @domachine tomorrow

**Comment by sthagen** [comment]
Hm, with my Safari on macOS Big Sur setup this current  branch completely fresh compiled allows me to change the invalid date per calendar pick ... just saying. I totally agree, that the side loading of a JSON document with schema violating content per copy-paste into the JSON editor  may be something hard to get right (match expectations of users for every use case).

**Comment by tschmidtb51** [comment]
@bentolor: Thanks for checking.

> IMHO the fix should be, that if the JSON value does not correctly resolve into a datetime, the date picker should start with an empty value.

That sounds perfect.

> Not sure if this can be be achieved easily to delay the erasure of this invalid date value to the moment where the user clicks first on the date picker widget. Will discuss with @domachine tomorrow

:+1:

**Comment by bentolor** [comment]
@tschmidtb51  The behaviour regarding invalid JSON date data is a separate bug and pre-existing, hence not related.

For sake of speed and clarity I'd rather prefer to move it into a separate ticket and approve & merge this well tested change.

**Review by tschmidtb51 — APPROVED** [review]
> @tschmidtb51 The behaviour regarding invalid JSON date data is a separate bug and pre-existing, hence not related.
>
> For sake of speed and clarity I'd rather prefer to move it into a separate ticket and approve & merge this well tested change.

Agreed. I approve the change.

**Pull request merged**
