### PR TITLE
Implement extlang restriction

### PR DESCRIPTION
**Pull request by tschmidtb51**
- resolves secvisogram/secvisogram#227
- implement restriction on multiple extlangs given

### CODE REVIEW

**Review by domachine — APPROVED** [review]
LGTM. Checked that the test fails without the patch :+1:

**Comment by domachine** [comment]
Ah, I overlooked that there is an outstanding review from @sthagen . I'm so sorry 🙈

**Review by sthagen — COMMENTED** [review]
🖼️ - 👍🏽 - 👍🏽

**Comment by tschmidtb51** [comment]
@domachine All good. You are free to update dependencies and release now ;-)

**Pull request merged**
