### PR TITLE
feat: add autohighlight to select inputs

### LINKED ISSUE #544: Add user input support
In fields, that suggest user input (e.g. `product_ids` or `cwe.*`) the user must actively select the value - if he just puts the correct value in, presses ENTER and then leaves the field, the entry is reset.
The behavior should be changed to automatically select the first matching entry so that pressing ENTER will lead to accepting the value.

### PR DESCRIPTION
**Pull request by MarcoKorinth**
Fixes #544 

# Changes
- Add autohighlight option to autocomplete components

### CODE REVIEW

**Review by tschmidtb51 — CHANGES_REQUESTED** [review]
This does not work for me - neither in the CWE fields nor in the product /group id space

BTW: Is it possible to add a test?

**Comment by MarcoKorinth** [comment]
Yes I tested it and it worked for me, but I will look into it again, specifically the fields you mentioned.

A simple enter key test is possible, I will add one.

**Comment by tschmidtb51** [comment]
BTW: Which browser did you use and which field for testing?

**Comment by MarcoKorinth** [comment]
I used firefox and the `Label of Flag` field in vulnerabilities.

Turns out we use different components for autocompletion in the code. 
The CWE and id inputs don't use the mui autocompletion component, so I have to refactor the other autocomplete component or implement the feature myself.

I'll look into it.

**Review by tschmidtb51 — APPROVED** [review]
LGTM

**Review by StefanNemeth — APPROVED** [review]

**Pull request merged**
