### PR TITLE
fix(max-doc): update max-doc to match current standard

### LINKED ISSUE #400: maxDoc is incomplete
The current maxDoc is missing some fields, e.g. `model_numbers`.

### PR DESCRIPTION
**Pull request by tschmidtb51**
fixed #400

### CODE REVIEW

**Comment by cloeser** [comment]
I changed the base branch to feat/wizzard

It looks as if there are some commits that are not relevant here.

**Comment by tschmidtb51** [comment]
> I changed the base branch to feat/wizzard
> 
> It looks as if there are some commits that are not relevant here.

Actually, I chose the main branch intentionally. It was the one that I created my branch from. And I think this file wasn't changed by feat/wizzard at all. (Although I realize now that I mentioned feat/wizzard in the issue :facepalm:).

**Comment by tschmidtb51** [comment]
I'll deal with that later today...

**Comment by cloeser** [comment]
Sorry :)

max-doc seems to be unchanged, min-doc had changes in feat/wizzard though.

**Comment by tschmidtb51** [comment]
> max-doc seems to be unchanged, min-doc had changes in feat/wizzard though.

My bad. Let's do this directly into main and I look into #399 later...

**Review by cloeser — APPROVED** [review]

**Review by mfd2007 — APPROVED** [review]

**Pull request merged**
